In [1]:
#Introductio to numpy
#Numpy is widely used to do numerical operations/computtions and
#also scientific computations along with high end mathematical operations

In [2]:
!pip install numpy

In [7]:
#shortname for numpy is np
import numpy as np

In [8]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [9]:
type(array_one)

numpy.ndarray

In [10]:
numbers = [10,20,30,40,50,60]
array_two = np.array(numbers) #---->We are passing a list to array
array_two

array([10, 20, 30, 40, 50, 60])

In [11]:
type(array_two)

numpy.ndarray

In [12]:
x = np.array(numbers)
x

array([10, 20, 30, 40, 50, 60])

In [13]:
#arrays are internally of float datatype.

In [14]:
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
array_of_one_int = np.ones((3,4),dtype = np.int16)
array_of_one_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)