In [5]:
import numpy as np

In [6]:
array_empty = np.empty((2,3))
array_empty

array([[ 6.30427764e-321,  3.52291614e-191, -2.36212516e-311],
       [ 2.48580178e+096,  6.71428845e-230,  2.88506173e-220]])

In [7]:
#Identity matrix implementation

In [8]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#to get even numbers between 1 to 30
even_array = np.arange(2,31,2)
even_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])