In [4]:
import numpy as np

In [4]:
array_of_float = np.arange(0,2,0.3)
array_of_float

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [12]:
#two dimensional array
ary_2d = np.arange([(1,2,3),(4,5,6)])

ary_2d

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(9,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(9,16)

array([ 9, 10, 11, 12, 13, 14, 15])

In [16]:
np.arange(9,13.642, 0.368)

array([ 9.   ,  9.368,  9.736, 10.104, 10.472, 10.84 , 11.208, 11.576,
       11.944, 12.312, 12.68 , 13.048, 13.416])

In [19]:
np.arange(9,13.642, -0.368)

array([], dtype=float64)

In [20]:
np.arange(9,13, -1)

array([], dtype=int32)

In [21]:
np.arange(9,3, -1)

array([9, 8, 7, 6, 5, 4])

In [22]:
a = np.arange(9,99, 6)
a

array([ 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93])

In [39]:
#a= 108
a = np.arange(108).resphae(12,9)
a

AttributeError: 'numpy.ndarray' object has no attribute 'resphae'

In [40]:
c = np.arange(24).reshape(2,3,4)

In [35]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
b = np.arange(12).reshape(3,4)

In [38]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a = np.arange(108).reshape(12,9)

In [6]:
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107]])

In [7]:
a.shape

(12, 9)

In [8]:
array_nd = np.arange(6).reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [9]:
#To print a 3D error

array_3D = np.arange(24).reshape(2,3,4)

In [10]:
array_3D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])