In [11]:
a = np.array([4,8,6])
b = np.array([5,7,2])

In [10]:
import numpy as np 

In [12]:
a

array([4, 8, 6])

In [13]:
b

array([5, 7, 2])

In [14]:
+ba

NameError: name 'ba' is not defined

In [15]:
a 

array([4, 8, 6])

In [16]:
b

array([5, 7, 2])

In [17]:
a+b

array([ 9, 15,  8])

In [18]:
a-b

array([-1,  1,  4])

In [19]:
a*b

array([20, 56, 12])

In [20]:
b-a

array([ 1, -1, -4])

In [21]:
b*a

array([20, 56, 12])

In [22]:
a/b

array([0.8       , 1.14285714, 3.        ])

In [23]:
b/a

array([1.25      , 0.875     , 0.33333333])

In [24]:
a%b

array([4, 1, 0], dtype=int32)

In [25]:
a>b

array([False,  True,  True])

In [26]:
a<b

array([ True, False, False])

In [27]:
a ==b

array([False, False, False])

In [28]:
b**3

array([125, 343,   8], dtype=int32)

In [29]:
a

array([4, 8, 6])

In [30]:
a*=5

In [31]:
a

array([20, 40, 30])

In [32]:
b

array([5, 7, 2])

In [33]:
b+=3

In [34]:
b

array([ 8, 10,  5])

In [35]:
ages =np.array([56,32,45,24,53,41])
ages

array([56, 32, 45, 24, 53, 41])

In [36]:
ages.sum()

251

In [37]:
ages.avg

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [38]:
ages.min()

24

In [39]:
ages.max()

56

In [42]:
ages.shape

(6,)

In [43]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
#To add up all the columns
numbers.sum(axis = 0)

array([12, 15, 18, 21])

In [45]:
#To add up all the columns
numbers.sum(axis = 1)

array([ 6, 22, 38])

In [46]:
#Intrduction to statistical functions
print(np.mean(numbers))

5.5


In [47]:
print(np.median(numbers))

5.5


In [48]:
print(np.mode(numbers))

AttributeError: module 'numpy' has no attribute 'mode'