In [2]:
import numpy as np

In [3]:
test_score = np.array([3.96,56.34,5.99,34.74,19.13,43.172])
test_score

array([ 3.96 , 56.34 ,  5.99 , 34.74 , 19.13 , 43.172])

In [4]:
print(np.mean(test_score))

27.221999999999998


In [5]:
sal = np.genfromtxt('salary.csv',delimiter = ',')
sal

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [6]:
#To find the number of rows.
sal.shape

(1147,)

In [13]:
mean = print(np.mean(sal))
median = print(np.median(sal))
sd =print(np.std(sal))
variance = print(np.var(sal))

55894.53879686138
48000.0
55170.37550939316
3043770333.8474483


In [15]:
print ('mean = %i' %mean)

TypeError: %i format: a number is required, not NoneType

In [16]:
print('mean =',mean)

mean = None


In [17]:
#looping through numpy
a = np.arange(11)**2

In [18]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [19]:
for i in sal:
    print(i**(1/2))

244.94897427831782
240.8318915758459
238.67760682560902
232.379000772445
264.5751311064591
197.48417658131498
189.73665961010275
161.24515496597098
207.3644135332772
273.8612787525831
203.4969287237525
189.73665961010275
161.24515496597098
200.0
200.0
248.99799195977465
173.20508075688772
150.5988047761336
166.1324772583615
209.76176963403032
180.0
236.64319132398464
511.41568219991063
200.0
277.48873851023217
175.55341067606747
204.93901531919198
707.1067811865476
278.5139134765084
244.94897427831782
204.93901531919198
254.95097567963924
244.94897427831782
346.41016151377545
232.379000772445
216.4717071582335
284.60498941515414
273.8612787525831
273.8612787525831
187.08286933869707
207.3644135332772
200.0
270.1851217221259
118.88650049522023
273.8612787525831
458.257569495584
300.0
195.95917942265424
324.387114417327
289.8275349237888
219.08902300206645
234.5207879911715
313.04951684997053
223.60679774997897
148.32396974191326
264.5751311064591
189.73665961010275
189.73665961010275
20

In [20]:
#looping through multi-dimensional array
family_accounts = np.array([['Harshini','manju','divya','soumya'],[65,87,64,31],[32,28,22,26]])
family_accounts

array([['Harshini', 'manju', 'divya', 'soumya'],
       ['65', '87', '64', '31'],
       ['32', '28', '22', '26']], dtype='<U8')

In [21]:
for i in family_accounts:
    print('i =',i)

i = ['Harshini' 'manju' 'divya' 'soumya']
i = ['65' '87' '64' '31']
i = ['32' '28' '22' '26']


In [23]:
for i in family_accounts.flatten():
    print('i =',i)

i = Harshini
i = manju
i = divya
i = soumya
i = 65
i = 87
i = 64
i = 31
i = 32
i = 28
i = 22
i = 26
